### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by SudaYDD** [WayneTomas/TransCP#1]
Great job on your work! May I ask when you plan to release the code?

**Comment by WayneTomas** [comment]
Thank you for your interest in our work. Recently, I have been primarily focused on neuralPS. I am doing my best to clean up the code and plan to make the organized code public before July. You can leave your email address, and I will notify you once it's done.

**Comment by SudaYDD** [comment]
Thank you for your response. I appreciate it. My email is gouchenyi0721@163.com. Best wishes for your ongoing work.

**Comment by beierdada** [comment]
Hi! I also want to the code.  Could you notify me? My email is 1151747338@qq.com. Best wishes for your ongoing work.

**Comment by WayneTomas** [comment]
Sorry for the late, i am trying my best to clean the code. :-D

**Comment by WayneTomas** [comment]
Hi~，the codes have been made public, and i will release the ckpts and other parts related to this paper in a few days.
