### ISSUE TITLE
Question about prototype.

### ISSUE THREAD

**Issue by zefanZhang-cn** [WayneTomas/TransCP#2]
感谢作者开源的代码！当我尝试在我的任务中加入您代码中的prototype代码时，初期还很正常，各个原型都可被更新到，但大概训练一半左右的时候全集中在一个原型上，请问这是什么原因呢？以及应该如何调整代码中的参数呢？

**Comment by WayneTomas** [comment]
感谢你的关注！不知道你具体做的是什么任务？我所实现的prototype本质上与深度聚类类似，所以我猜测可能你需要针对的任务调整一下原型数目和特征维度。如果你前面的特征不是特别好的话，可能需要增加映射层进一步降维维压缩后再接入原型学习部分，避免出现维度灾难；另外可以考虑是否是数据集比较小，但原型数目过多，这种情况可以尝试缩小原型数目看看。

**Comment by zefanZhang-cn** [comment]
> 感谢你的关注！不知道你具体做的是什么任务？我所实现的prototype本质上与深度聚类类似，所以我猜测可能你需要针对的任务调整一下原型数目和特征维度。如果你前面的特征不是特别好的话，可能需要增加映射层进一步降维维压缩后再接入原型学习部分，避免出现维度灾难；另外可以考虑是否是数据集比较小，但原型数目过多，这种情况可以尝试缩小原型数目看看。

感谢您的回复，您的思路解决了我的困惑。
